FROM nginx:1.26.2-alpine-perl

RUN rm /etc/nginx/conf.d/default.conf

# COPIANDO O ARQUIVO DE CONFIGURAÇÃO DO NGINX
COPY nginx.conf /etc/nginx/conf.d

RUN mkdir /var/www/html -p && touch /var/www/html/index.php

# COPY html /usr/share/nginx/html
# ENTRYPOINT [ "/docker-entrypoint.sh" ]
# CMD [ "nginx", "-g", "daemon off;" ]