FROM nginx:1.26.2-alpine-perl

RUN rm /etc/nginx/conf.d/default.conf

# COPIANDO O ARQUIVO DE CONFIGURAÇÃO DO NGINX
COPY nginx.conf /etc/nginx/conf.d
COPY nginx.conf /etc/nginx/sites-available/myserver

RUN mkdir /var/www/html -p && touch /var/www/html/index.php

RUN cd /etc/nginx/sites-available/
RUN ln -s /etc/nginx/sites-available/myserver